import Link from 'next/link';
import type { Metadata } from 'next';
import { Breadcrumbs } from '@/components/layout/Breadcrumbs';
import { CALCULATORS } from '@/components/calculators/registry';
import { CONTENT_PAGES } from '@/content';
import { CONTACT_EMAIL } from '@/lib/seo';

export const metadata: Metadata = {
  title: 'About',
  description: 'About MeasureToBuild: one tested calculation engine, visible assumptions, no invented prices — and the limits it will not hide from you.',
  alternates: { canonical: '/about' },
  openGraph: {
    title: 'About',
    description: 'About MeasureToBuild: one tested calculation engine, visible assumptions, no invented prices — and the limits it will not hide from you.',
    url: '/about',
    type: 'website',
  },
};

export default function AboutPage() {
  return (
    <div className="container content-page section">
      <Breadcrumbs items={[{ label: 'About' }]} />
      <header className="page-intro" style={{ paddingLeft: 0 }}>
        <div className="eyebrow">About the platform</div>
        <h1>Built around useful project planning.</h1>
        <p className="lede">
          The goal is simple: turn real outdoor-project measurements into understandable material quantities,
          user-entered cost estimates and practical shopping lists — and be honest about everything those numbers
          depend on.
        </p>
        <p className="page-updated">Last updated: October 1, 2026</p>
      </header>

      <div className="content-page-grid">
        <div className="copy content-body">
          <section id="what" aria-labelledby="what-heading">
            <h2 id="what-heading">What this site is</h2>
            <p>
              {CALCULATORS.length} calculators covering landscaping materials, driveways, hardscape, fences and
              decks, plus {CONTENT_PAGES.length} guides explaining the judgement calls behind each calculation.
              Results can be combined in Project Mode — one browser-local plan of materials, quantities, costs and
              a printable shopping list, with no account required.
            </p>
            <p>
              The site is designed around a tested calculation layer rather than a collection of isolated
              calculator formulas. That is what makes it possible to reuse the same logic in calculator pages,
              guides and Project Mode while keeping assumptions visible everywhere.
            </p>
          </section>

          <section id="how" aria-labelledby="how-heading">
            <h2 id="how-heading">How it is built</h2>
            <p>
              One typed engine owns every formula. The interface converts your form into an engine input, calls it,
              and presents the typed result — it never does arithmetic of its own, so two pages cannot disagree
              about the same measurement. Unit tests cover the quantity behaviour, and the{' '}
              <Link href="/methodology">methodology page</Link> publishes the assumptions file as a reference table.
            </p>
            <p>
              Guide worked examples are generated by calling the engine too, which means the number in an article
              and the number in the calculator are produced by the same code path.
            </p>
          </section>

          <section id="not" aria-labelledby="not-heading">
            <h2 id="not-heading">What this site does not pretend to be</h2>
            <p>
              It is not a substitute for structural engineering, property surveying, local code review, permit
              determinations, manufacturer instructions or a professional site evaluation where those are needed.
              It also does not pretend to know today&apos;s prices: cost fields only ever use prices you enter, and
              a missing price stays missing.
            </p>
            <p>
              There are no accounts, and advertising is not currently served on this site. The only third-party
              service currently used for site measurement is Google Analytics. It helps us understand how the site
              is used, including information such as pages viewed, approximate location, and device information. The{' '}
              <Link href="/privacy">privacy page</Link> explains what is collected and how it is handled.
            </p>
            <p>
              There is no manufactured authority either — no fake bylines, no review counts, no star ratings. The
              trust comes from showing the method, the sources and the limits.
            </p>
          </section>

          <section id="contact" aria-labelledby="contact-heading">
            <h2 id="contact-heading">Contact</h2>
            {CONTACT_EMAIL ? (
              <p>
                Questions, corrections or a calculation that looks wrong: email{' '}
                <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. Corrections with a measurement and the
                numbers you expected are the most useful kind.
              </p>
            ) : (
              <p>
                Contact details for this deployment are published by its operator on this page once configured.
              </p>
            )}
            <p>
              See the <Link href="/how-it-works">how it works page</Link> for the workflow, the{' '}
              <Link href="/guides">guide library</Link> for the content, and the <Link href="/terms">terms of use</Link>{' '}
              for the rules of using the estimates.
            </p>
          </section>
        </div>

        <aside className="sticky-shell">
          <div className="cta-card">
            <h2>The short version</h2>
            <ul className="copy-list">
              <li>One engine, every calculator.</li>
              <li>Assumptions published and overridable.</li>
              <li>Prices only from you — never invented.</li>
              <li>No account required.</li>
              <li>Project data stays in your browser.</li>
            </ul>
            <div className="content-actions">
              <Link className="button button-primary" href="/calculators">Browse calculators</Link>
            </div>
          </div>
          <div className="content-toc">
            <h2>Read next</h2>
            <ol>
              <li>
                <Link href="/how-it-works">How it works</Link>
              </li>
              <li>
                <Link href="/methodology">Methodology</Link>
              </li>
              <li>
                <Link href="/privacy">Privacy</Link>
              </li>
            </ol>
          </div>
        </aside>
      </div>
    </div>
  );
}
