
          <section id="one-engine" aria-labelledby="one-engine-heading">
            <h2 id="one-engine-heading">5. One engine, one meaning per number</h2>
            <p>
              Because every calculator dispatches through the same engine, shared concepts have one definition:
              &quot;waste&quot;, &quot;compaction&quot; and &quot;tons&quot; mean the same thing on the gravel page
              and the driveway page. The engine-bridge layer only adds presentation summaries on top of typed
              results — it never recomputes them.
            </p>
            <p>
              The engine is covered by unit tests that assert quantity behaviour (spacing, rounding, waste
              interaction) rather than snapshots, so a formula cannot change silently.
            </p>
          </section>

          <section id="validation" aria-labelledby="validation-heading">
            <h2 id="validation-heading">6. Validation before arithmetic</h2>
            <p>
              Engine inputs are validated at the boundary: empty, negative or nonsensical values produce a named
              error instead of a plausible-looking wrong number. The interface shows those errors next to the field
              that caused them — you are told which input rejected the calculation, not given a NaN.
            </p>
          </section>

          <section id="assumptions" aria-labelledby="assumptions-heading">
            <h2 id="assumptions-heading">7. Assumptions are data, not prose</h2>
            <p>
              Waste percentages, densities, bag sizes, compaction factors, joint widths and rounding steps live in
              one centralized assumptions file shared by every calculator. The <Link href="/methodology">methodology
              page</Link> renders that file as a reference table, and every calculator shows the assumptions that
              applied to your result.
            </p>
            <p>
              Where a number matters to your project — waste, density, compaction — the calculator lets you override
              it rather than forcing a default on you.
            </p>
          </section>

          <section id="provenance" aria-labelledby="provenance-heading">
            <h2 id="provenance-heading">8. Results carry their provenance</h2>
            <p>
              Each result shows the inputs it was calculated from and the headline outputs that matter for ordering.
              When something cannot be derived from what you entered (for example, edge restraint without a
              perimeter), the result says so instead of inventing a figure.
            </p>
            <p>
              Guide pages work the same way: every worked example states its inputs and is generated by calling the
              engine, so a guide and a calculator can never disagree about the same measurement.
            </p>
          </section>
